name: Process Votes

on:
  push:
    branches:
      - main
      - master
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  count_votes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Vote Counter
        run: |
          node count_votes.js

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: Update vote results
          add: 'vote_results.json'
